In [1]:
import numpy as np

In [3]:
#generate arr1:

#[[ 0  4  8 12 16]
# [ 1  5  9 13 17]
# [ 2  6 10 14 18]
# [ 3  7 11 15 19]]
arr = np.arange(0, 20)
arr1 = arr.reshape((4, 5), order='F')
print(arr1)

[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]


In [5]:
#generate arr2

#[[ 0  1  4  9 16]
# [ 1  4  9 16 25]
# [ 4  9 16 25 36]
# [ 9 16 25 36 49]]

# method 1: with a single for loop

arr2 = np.empty((4, 5), dtype=int)
for i in range(4):
    arr2[i] = np.arange(0+i, 5+i)**2

print(arr2)

# method 2: tile method

A = np.tile(np.arange(5), (4,1))
B = np.tile(np.arange(4), (5,1)).T
arr2 = (A+B)**2
print(arr2)

# method 3: with mgrid method

A, B = np.mgrid[0:4, 0:5]
arr2 = (A+B)**2
print(arr2)

[[ 0  1  4  9 16]
 [ 1  4  9 16 25]
 [ 4  9 16 25 36]
 [ 9 16 25 36 49]]
[[ 0  1  4  9 16]
 [ 1  4  9 16 25]
 [ 4  9 16 25 36]
 [ 9 16 25 36 49]]
[[ 0  1  4  9 16]
 [ 1  4  9 16 25]
 [ 4  9 16 25 36]
 [ 9 16 25 36 49]]


In [6]:
#generate arr3

#[[0 1 0 1 0 1]
# [1 0 1 0 1 0]
# [0 1 0 1 0 1]
# [1 0 1 0 1 0]
# [0 1 0 1 0 1]
# [1 0 1 0 1 0]]

arr = [[0, 1], [1, 0]]

arr3 = np.tile(arr, (3, 3))
print(arr3)

[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


In [11]:
#a[start:stop]  # items start through stop-1
#a[start:]      # items start through the rest of the array
#a[:stop]       # items from the beginning through stop-1
#a[:]           # a copy of the whole array

#a[start:stop:step] # start through not past stop, by step

#a[-1]    # last item in the array
#a[-2:]   # last two items in the array
#a[:-2]   # everything except the last two items

#a[::-1]    # all items in the array, reversed
#a[1::-1]   # the first two items, reversed
#a[:-3:-1]  # the last two items, reversed
#a[-3::-1]  # everything except the last two items, reversed

#a[start:stop:step] is equivalent to: a[slice(start, stop, step)]

#extract from arr1

#[[ 6 18 10]
# [ 7 19 11]
# [ 5 17  9]]

print(arr1)
arr = arr1[[2, 3, 1], :]
arr = arr[:, [1, 4, 2]]
print(arr)


[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]
[[ 6 18 10]
 [ 7 19 11]
 [ 5 17  9]]


In [8]:
#Replace all the items with value 0 of arr3 by -1
print(arr3)
arr3[arr3 == 0] = -1
print(arr3)

[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]
[[-1  1 -1  1 -1  1]
 [ 1 -1  1 -1  1 -1]
 [-1  1 -1  1 -1  1]
 [ 1 -1  1 -1  1 -1]
 [-1  1 -1  1 -1  1]
 [ 1 -1  1 -1  1 -1]]


In [13]:
#Create a random vector of size 20 (all values between [0,1)) 
#and replace:the maximum value by −1and the second maximum value by −2

arr = np.random.rand(20)
print(arr)
arr[np.argmax(arr)] = -1
arr[np.argmax(arr)] = -2
print(arr)

[0.04314016 0.66661053 0.05237606 0.41860588 0.13572803 0.66466262
 0.80793444 0.86294351 0.72646594 0.9892431  0.95884199 0.519671
 0.91147144 0.37475146 0.86596645 0.06410541 0.26700592 0.11173049
 0.54011008 0.74951343]
[ 0.04314016  0.66661053  0.05237606  0.41860588  0.13572803  0.66466262
  0.80793444  0.86294351  0.72646594 -1.         -2.          0.519671
  0.91147144  0.37475146  0.86596645  0.06410541  0.26700592  0.11173049
  0.54011008  0.74951343]


In [10]:
arr = np.arange(0, 20)
arr1 = arr.reshape((4, 5), order='F')
print(arr1)

np.mean(arr1) # calculates the mean of the array arr1
print(arr1.mean())

#the mean of each column is 0
normed = (arr1 - arr1.mean(axis=0)) / arr1.std(axis=0)
print(normed)
print(normed.mean(axis=0))


#the standard deviation of each column is 1
normed.std(axis=0)
print(normed.std(axis=0))

[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]
9.5
[[-1.34164079 -1.34164079 -1.34164079 -1.34164079 -1.34164079]
 [-0.4472136  -0.4472136  -0.4472136  -0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136   0.4472136   0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079  1.34164079  1.34164079  1.34164079]]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [14]:
#Let A be a matrix and b be a vector defined by:
#>>> V = np.random.rand(3, 3)
#>>> A = V + V.T
#>>> b = np.random.rand(3)

#Solve the linear system Ax=b

V = np.random.rand(3, 3)
print(V)
A = (V * (V.T))
print(A)
b = np.random.rand(3)
print(b)

x = np.linalg.solve(A, b)
print(x)

print('the linear system "Ax=b" is:')
np.allclose(np.dot(A, x), b)


[[0.47290302 0.87904604 0.84863549]
 [0.5694917  0.62999019 0.38379933]
 [0.89995326 0.48824797 0.8627575 ]]
[[0.22363727 0.50060943 0.76373228]
 [0.50060943 0.39688764 0.18738924]
 [0.76373228 0.18738924 0.74435051]]
[0.08709131 0.30494596 0.54427692]
[ 0.74463021 -0.17635892  0.01158937]
the linear system "Ax=b" is:


True